cms/blueprints/admin.py
# -*- coding: utf-8 -*-

from flask import Blueprint, render_template, url_for, redirect, request, flash, current_app
from flask_login import login_required, current_user

from cms.extensions import db
from cms.forms import SettingForm, PostForm, CategoryForm, LinkForm
from cms.utils import redirect_back
from cms.models import Post, Category, Comment, Admin, Link

# 创建蓝本，第一个参数为蓝本的名称，第二个参数是包或模块的名称
# 使用__name__方便判断蓝本的根目录，寻找模板文件夹和静态文件夹
admin_bp = Blueprint('admin',__name__)

@admin_bp.route('/settings', methods=['POST', 'GET'])
@login_required
def settings():
    form = SettingForm()
    if form.validate_on_submit():
        current_user.name = form.name.data
        current_user.blog_title = form.blog_title.data
        current_user.blog_sub_title = form.blog_sub_title.data
        current_user.about = form.about.data
        db.session.commit()
        flash('Setting updated.', 'success')
        return redirect(url_for('blog.index'))
    form.name.data = current_user.name
    form.blog_title.data = current_user.blog_title
    form.blog_sub_title.data = current_user.blog_sub_title
    form.about.data = current_user.about
    return render_template('admin/settings.html', form=form)

# ----------------------------------------------------------------------------------

@admin_bp.route('/post/manage')
@login_required
def manage_post():
    page = request.args.get('page', 1, type=int)
    pagination = Post.query.order_by(Post.timestamp.desc()).paginate(page, per_page=current_app.config['CMS_MANAGE_POST_PER_PAGE'])
    posts = pagination.items
    return render_template('/admin/manage_post.html', pagination=pagination, posts=posts, page=page)

@admin_bp.route('/post/new', methods=['GET', 'POST'])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        title = form.title.data
        body = form.body.data
        category = Category.query.get(form.category.data)
        post = Post(title=title, body=body, category=category)
        db.session.add(post)
        db.session.commit()
        flash('Post created !', 'sucess')
        return redirect(url_for('blog.show_post', post_id=post.id))
    return render_template('/admin/new_post.html', form=form)

@admin_bp.route('/post/<int:post_id>/edit', methods=['GET', 'POST'])
@login_required
def edit_post(post_id):
    form = PostForm()
    # 获取对应文章id
    post = Post.query.get_or_404(post_id)
    if form.validate_on_submit():
        post.title = form.title.data
        post.body = form.body.data
        post.category = Category.query.get(form.category.data)
        db.session.commit()
        flash('Post updated.', 'success')
        return redirect(url_for('blog.show_post', post_id=post.id))
    form.title.data = post.title
    form.body.data = post.body
    form.category.data = post.category_id 
    return render_template('/admin/edit_post.html', form=form)

@admin_bp.route('/post/<int:post_id>/delete', methods=['POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    db.session.delete(post)
    db.session.commit()
    flash('Post delete.','success')
    return redirect_back()

# ----------------------------------------------------------------------------------

@admin_bp.route('/post/<int:post_id>/set-comment', methods=['POST'])
@login_required
def set_comment(post_id):
    post = Post.query.get_or_404(post_id)
    if post.can_comment:
        post.can_comment = False
        flash('Comment disabled.','info')
    else:
        post.can_comment = True
        flash('Comment enabled.','info')
    db.session.commit()
    return redirect(url_for('blog.show_post', post_id=post.id))

@admin_bp.route('/comment/manage')
@login_required
def manage_comment():
    filter_rule = request.args.get('filter', 'all') # 获取过滤规则，以显示不同的评论
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['CMS_COMMENT_PER_PAGE']

    if filter_rule == 'unread':
        filtered_comments = Comment.query.filter_by(reviewed=False)
    elif filter_rule == 'admin':
        filtered_comments = Comment.query.filter_by(from_admin=True)
    else:
        filtered_comments = Comment.query
    
    pagination = filtered_comments.order_by(Comment.timestamp.desc()).paginate(page, per_page=per_page)
    comments = pagination.items

    return render_template('/admin/manage_comment.html', comments=comments, pagination=pagination)

@admin_bp.route('/comment/<int:comment_id>/approve', methods=['POST'])
@login_required
def approve_comment(comment_id):
    comment = Comment.query.get_or_404(comment_id)
    comment.reviewed = True
    db.session.commit()
    flash('Comment published.','success')
    return redirect_back()


@admin_bp.route('/comment/<int:comment_id>/delete', methods=['POST'])
@login_required
def delete_comment(comment_id):
    comment = Comment.query.get_or_404(comment_id)
    db.session.delete(comment)
    db.session.commit()
    flash('Comment deleted.','success')
    return redirect_back()

# ----------------------------------------------------------------------------------

@admin_bp.route('/category/manage')
@login_required
def manage_category():
    return render_template('admin/manage_category.html')


@admin_bp.route('/category/new', methods=['GET', 'POST'])
@login_required
def new_category():
    form = CategoryForm()
    form = CategoryForm()
    if form.validate_on_submit():
        name = form.name.data
        category = Category(name=name)
        db.session.add(category)
        db.session.commit()
        flash('Category created.', 'success')
        return redirect(url_for('.manage_category'))
    return render_template('admin/new_category.html', form=form)


@admin_bp.route('/category/<int:category_id>/edit', methods=['GET', 'POST'])
@login_required
def edit_category(category_id):
    form = CategoryForm()
    category = Category.query.get_or_404(category_id)
    if category_id == 1:
        flash('You can not edit the default category.', 'warning')
        return redirect(url_for('blog.index'))
    if form.validate_on_submit():
        category.name = form.name.data
        db.session.commit()
        flash('Category updated.','success')
        return redirect(url_for('.manage_category'))
    form.name.data = category.name
    return render_template('admin/edit_category.html', form=form)


@admin_bp.route('/category/<int:category_id>/delete', methods=['POST'])
@login_required
def delete_category(category_id):
    category = Category.query.get_or_404(category_id)
    if category.id == 1:
        flash('You can not delete the default category.', 'warning')
        return redirect(url_for('blog.index'))
    category.delete() # 此方法已在category model中定义
    flash('Category deleted.', 'success')
    return redirect(url_for('.manage_category'))

# ----------------------------------------------------------------------------------

@admin_bp.route('/link/manage')
@login_required
def manage_link():
    return render_template('admin/manage_link.html')


@admin_bp.route('/link/new', methods=['GET', 'POST'])
@login_required
def new_link():
    form = LinkForm()
    if form.validate_on_submit():
        name = form.name.data
        url = form.url.data
        icon = form.icon.data
        link = Link(name=name, url=url, icon=icon)
        db.session.add(link)
        db.session.commit()
        flash('Link created.', 'success')
        return redirect(url_for('.manage_link'))
    return render_template('admin/new_link.html', form=form)


@admin_bp.route('/link/<int:link_id>/edit', methods=['GET', 'POST'])
@login_required
def edit_link(link_id):
    form = LinkForm()
    link = Link.query.get_or_404(link_id)
    if form.validate_on_submit():
        link.name = form.name.data
        link.url = form.url.data
        link.icon = form.name.data
        db.session.commit()
        flash('Link updated.', 'success')
        return redirect(url_for('.manage_link'))
    form.name.data = link.name
    form.url.data = link.url
    form.icon.data = link.icon
    return render_template('admin/edit_link.html', form=form)


@admin_bp.route('/link/<int:link_id>/delete', methods=['POST'])
@login_required
def delete_link(link_id):
    link = Link.query.get_or_404(link_id)
    db.session.delete(link)
    db.session.commit()
    flash('Link deleted.', 'success')
    return redirect(url_for('.manage_link'))

cms/blueprints/auth.py
# -*- coding: utf-8 -*-

from flask import Blueprint, render_template, redirect, url_for, flash
from flask_login import login_user, current_user, login_required, logout_user

from cms.models import Admin
from cms.forms import LoginForm
from cms.utils import redirect_back

auth_bp = Blueprint('auth', __name__)

@auth_bp.route('/login', methods=['GEt', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('blog.index'))
    
    form = LoginForm()
    if form.validate_on_submit():
        username = form.username.data
        password = form.password.data
        remember = form.remember.data
        admin = Admin.query.first()
        if admin:
            if username == admin.username and admin.validate_password(password):
                login_user(admin, remember)
                flash('Welcom back.', 'info')
                return redirect_back()
            flash('Invalid username or password.', 'warning')
        else:
            flash('No account.','warning')
    return render_template('auth/login.html', form=form)

@auth_bp.route('/logout')
@login_required
def logout():
    logout_user()
    flash('Logout Sucess.','info')
    return redirect_back()

cms/blueprints/blog.py
# -*- coding: utf-8 -*-

from flask import render_template, flash, redirect, url_for, request, current_app, Blueprint, abort, make_response
from flask_login import current_user

from cms.emails import send_new_comment_email, send_new_reply_email
from cms.extensions import db
from cms.forms import CommentForm, AdminCommentForm
from cms.models import Post, Category, Comment
from cms.utils import redirect_back

blog_bp = Blueprint('blog', __name__)



@blog_bp.route('/')
def index():
    """ posts = Post.query.order_by(Post.timestamp.desc()).all() """
    page = request.args.get('page', 1, type=int) # 通过查询字符串获取当前页数
    per_page = current_app.config['CMS_POST_PER_PAGE'] # 每页数量
    # paginate方法的page默认值为1，per_page的默认值为20,pagination为分页对象
    pagination = Post.query.order_by(Post.timestamp.desc()).paginate(page, per_page=per_page)
    posts = pagination.items # 当前页数的记录列表
    return render_template('blog/index.html', pagination=pagination, posts=posts)

@blog_bp.route('/about')
def about():
    return render_template('blog/about.html')

@blog_bp.route('/category/<int:category_id>')
def show_category(category_id):
    category = Category.query.get_or_404(category_id)
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['CMS_POST_PER_PAGE']
    # 使用with_parent筛选所属分类文章
    pagination = Post.query.with_parent(category).order_by(Post.timestamp.desc()).paginate(page, per_page)
    posts = pagination.items
    return render_template('blog/category.html', category=category, pagination=pagination, posts=posts)

@blog_bp.route('/post/<int:post_id>', methods=['GET', 'POST'])
def show_post(post_id):
    post = Post.query.get_or_404(post_id)
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['CMS_COMMENT_PER_PAGE']
    # 通过filter_by过滤器获取通过审核的评论
    pagination = Comment.query.with_parent(post).filter_by(reviewed=True).order_by(Comment.timestamp.asc()).paginate(
        page, per_page)
    # 评论分页
    comments = pagination.items

    if current_user.is_authenticated: # 已登录，使用管理员表单
        form = AdminCommentForm()
        form.author.data = current_user.name
        form.email.data = current_app.config['CMS_EMAIL']
        form.site.data = url_for('.index')
        from_admin = True
        reviewed = True
    else:
        form = CommentForm()
        from_admin = False
        reviewed = False
    
    if form.validate_on_submit():
        author = form.author.data
        email = form.email.data
        site = form.site.data
        body = form.body.data
        comment = Comment(
            author=author, email=email, site=site, body=body,
            from_admin=from_admin, post=post, reviewed=reviewed
        )
        replied_id = request.args.get('reply')
        if replied_id:
            replied_comment = Comment.query.get_or_404(replied_id)
            comment.replied = replied_comment
            send_new_reply_email(replied_comment)
        db.session.add(comment)
        db.session.commit()
        
        # 消息闪现提醒
        if current_user.is_authenticated:
            flash('Comment published.', 'success')
        else:
            flash('Thanks, your comment will be published after reviewed.', 'info')
            # admin_email = current_app.config['CMS_EMAIL']
            send_new_comment_email(post)
        return redirect(url_for('.show_post', post_id=post_id))
    return render_template('blog/post.html', post=post, comments=comments, pagination=pagination, form=form)

# 回复功能
@blog_bp.route('/reply/comment/<int:comment_id>')
def reply_comment(comment_id):
    comment = Comment.query.get_or_404(comment_id)
    if not comment.post.can_comment:
        flash('Comment is disabled.', 'warning')
        return redirect(url_for('.show_post', post_id=comment.post.id))
    return redirect(
        url_for('.show_post', post_id=comment.post_id, reply=comment_id, author=comment.author) + '#comment-form')

# 主题切换
@blog_bp.route('/change-theme/<theme_name>')
def change_theme(theme_name):
    if theme_name not in current_app.config['CMS_THEMES'].keys():
        abort(404)
    
    response = make_response(redirect_back()) # 生成一个重定向啊应
    response.set_cookie('theme', theme_name, max_age=30*24*60*60)
    return response

# 搜索功能
@blog_bp.route('/search')
def search():
    q = request.args.get('q', '')
    if q == '':
        flash('Enter keywords about category or post title', 'warning')
        return redirect_back()
    
    # 获取查询类型，再模板中给出
    what = request.args.get('what', 'title')
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['CMS_POST_PER_PAGE']

    if what == 'title':
        pagination = Post.query.whooshee_search(q).paginate(page, per_page)
    elif what == 'category':
        pagination = Category.query.whooshee_search(q).paginate(page, per_page)
    else:
        redirect_back()

    results = pagination.items

    return render_template('search.html', q=q, results=results, pagination=pagination, what=what)

# 文章归档
@blog_bp.route('/archive')
def archive():
    """按时间归档文章"""
    posts = Post.query.order_by(Post.timestamp.desc()).all()
    # 按月份分组所有post
    data = {}
    years = reversed(list(set([post.timestamp.year for post in posts])))
    for year in years:
        months = reversed(list(set([post.timestamp.month for post in posts if post.timestamp.year == year])))
        for month in months:
            post_items = [post for post in posts if post.timestamp.month == month]
            data[(year, month)] = post_items
    return render_template('blog/archive.html', data=data)

cms/templates/base.html
{% from 'bootstrap/nav.html' import render_nav_item %}
{# 使用bootstrap-flask扩展，渲染导航栏 #}

<!DOCTYPE html>
<html lang="en">
<head>
    {% block head %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}{% endblock title %} - {{ admin.blog_title|default('Blog Title') }}</title>
    <link rel="icon" href="{{ url_for('static', filename='favicon.ico') }}">
    <link rel="stylesheet"
            href="{{ url_for('static', filename='css/%s.min.css' % request.cookies.get('theme', 'perfect_blue')) }}"
            type="text/css">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}" type="text/css">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/fontawesome_all.min.css') }}" type="text/css">
    {% endblock head %}
</head>

<body>
    {% block nav %}
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <div class="container">
            <a class="navbar-brand" href="{{ url_for('blog.index') }}">{{ admin.blog_title }}</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01"
                    aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarColor01">
                <ul class="navbar-nav mr-auto">
                    <i class="fas fa-home fa-fw" id="navicon"></i>{{ render_nav_item('blog.index', 'Home') }}
                    <i class="fas fa-user fa-fw" id="navicon"></i>{{ render_nav_item('blog.about', 'About') }}
                    <i class="fas fa-archive fa-fw" id="navicon"></i>{{ render_nav_item('blog.archive', 'Archive') }} 
                </ul>
                <!-- 搜索 -->
                <form class="form-inline my-2 my-lg-0" action="{{ url_for('blog.search') }}">
                    <input class="form-control mr-sm-2" name="q" type="text" placeholder="category or post title">
                    <button class="btn btn-secondary my-2 my-sm-0" type="submit">
                        <i class="fas fa-search"></i>
                    </button>
                </form>               
                <!-- 管理员导航 -->
                <ul class="nav navbar-nav navbar-right">
                    {% if current_user.is_authenticated %}
                        <li class="nav-item dropdown">
                            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button"
                               aria-haspopup="true"
                               aria-expanded="false">
                                New <span class="caret"></span>
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="{{ url_for('admin.new_post') }}">Post</a>
                                <a class="dropdown-item" href="{{ url_for('admin.new_category') }}">Category</a>
                                <a class="dropdown-item" href="{{ url_for('admin.new_link') }}">Link</a>
                            </div>
                        </li>
                        <li class="nav-item dropdown">
                            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button"
                               aria-haspopup="true"
                               aria-expanded="false">
                                Manage <span class="caret"></span>
                                {% if unread_comments %}
                                    <span class="badge badge-success">new</span>
                                {% endif %}
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="{{ url_for('admin.manage_post') }}">Post</a>
                                <a class="dropdown-item" href="{{ url_for('admin.manage_category') }}">Category</a>
                                <a class="dropdown-item" href="{{ url_for('admin.manage_comment') }}">
                                    Comment
                                    {% if unread_comments %}
                                        <span class="badge badge-success">{{ unread_comments }}</span>
                                    {% endif %}
                                </a>
                                <a class="dropdown-item" href="{{ url_for('admin.manage_link') }}">Link</a>
                            </div>
                        </li>
                        {{ render_nav_item('admin.settings', 'Settings') }}
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
    {% endblock %}
    
    <main class="container">
        {% for message in get_flashed_messages(with_categories=True) %}
            <div class="alert alert-{{ message[0] }}" role="alert">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                {{ message[1] }}
            </div>
        {% endfor %}
        
        {% block content %}{% endblock %}

        <div class="goTop" id="js-go_top"><span class="fas fa-hand-point-up"></span></div>

        {% block footer %}
        <footer>
            <p class="float-left">
                <small> &copy; 2019 <a href="https://shansan.top" title="Written by shansan">ShanSan</a> -
                    <a href="https://github.com/yeshan333" title="Fork me on GitHub">GitHub</a>
                </small>
            </p>
            <p class="float-right">
                <small>
                    <!-- next参数用与存储当前页面路径，便于redirect_back -->
                    {% if current_user.is_authenticated %}
                        <a class="btn btn-secondary" href="{{ url_for('auth.logout', next=request.full_path) }}">Logout</a>
                    {% else %}
                        <a class="btn btn-secondary" href="{{ url_for('auth.login', next=request.full_path) }}">Login</a>
                    {% endif %}
                </small>
            </p>
        </footer>   
        {% endblock %}
    </main>

    {% block scripts %}
        <script type="text/javascript" src="{{ url_for('static', filename='js/jquery-3.3.1.min.js') }}"></script>
        <script type="text/javascript" src="{{ url_for('static', filename='js/popper.min.js') }}"></script>
        <script type="text/javascript" src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
        <script type="text/javascript" src="{{ url_for('static', filename='js/GoToTop.js') }}"></script>
        <script type="text/javascript" src="{{ url_for('static', filename='js/script.js')}}"></script>
        {{ moment.include_moment(local_js=url_for('static', filename='js/moment-with-locales.min.js')) }}
    {% endblock %}
</body>
</html>

cms/templates/macros.html
{# 导航栏激活状态 #}
{% macro nav_link(endpoint, text) %}
    <li class="nav-item {% if request.endpoint and request.endpoint == endpoint %}active{% endif %}">
        <a class="nav-link" href="{{ url_for(endpoint, **kwargs) }}">{{ text }}</a>
    </li>
{%- endmacro %}

{# 分页部件 #}
{% macro pager(pagination, fragment='') %}
<nav aria-label="Page navigation">
    <ul class="pagination">
        <li class="page-item {% if not pagination.has_prev %}disabled{% endif %}">
            <a class="page-link" href="{{ url_for(request.endpoint, page=pagination.prev_num, **kwargs) + fragment if pagination.has_prev else '#'}}">
                <span aria-hidden="true">&larr;</span>Newer
            </a>
        </li>
    </ul>
    <ul class="pagination">
        <li class="page-item {% if not pagination.has_next %}disabled{% endif %}">
            <a class="page-link" href="{{ url_for(request.endpoint, page=pagination.next_num, **kwargs) + fragment if pagination.has_next else '#'}}">
                Older<span aria-hidden= "true">&rarr;</span>
            </a>
        </li>
    </ul>
</nav>
{% endmacro %}

{# 搜索 #}
{% macro category_card(category) %}
    <div class="list-group">
        <a href="{{ url_for('blog.show_category', category_id=category.id) }}" class="list-group-item list-group-item-action">
            {{ category.name }}
        </a>
    </div>
{% endmacro %}

{% macro post_card(post) %}
    <div class="list-group">
        <a href="{{ url_for('blog.show_post', post_id=post.id) }}" class="list-group-item list-group-item-action">
            {{ post.title }}
        </a>
    </div>
{% endmacro %}

{# high一下 #}
{% macro high() %}
<li> <a title="把这个链接拖到你的Chrome收藏夹工具栏中" href='javascript:(function() {
    function c() {
        var e = document.createElement("link");
        e.setAttribute("type", "text/css");
        e.setAttribute("rel", "stylesheet");
        e.setAttribute("href", f);
        e.setAttribute("class", l);
        document.body.appendChild(e)
    }
 
    function h() {
        var e = document.getElementsByClassName(l);
        for (var t = 0; t < e.length; t++) {
            document.body.removeChild(e[t])
        }
    }
 
    function p() {
        var e = document.createElement("div");
        e.setAttribute("class", a);
        document.body.appendChild(e);
        setTimeout(function() {
            document.body.removeChild(e)
        }, 100)
    }
 
    function d(e) {
        return {
            height : e.offsetHeight,
            width : e.offsetWidth
        }
    }
 
    function v(i) {
        var s = d(i);
        return s.height > e && s.height < n && s.width > t && s.width < r
    }
 
    function m(e) {
        var t = e;
        var n = 0;
        while (!!t) {
            n += t.offsetTop;
            t = t.offsetParent
        }
        return n
    }
 
    function g() {
        var e = document.documentElement;
        if (!!window.innerWidth) {
            return window.innerHeight
        } else if (e && !isNaN(e.clientHeight)) {
            return e.clientHeight
        }
        return 0
    }
 
    function y() {
        if (window.pageYOffset) {
            return window.pageYOffset
        }
        return Math.max(document.documentElement.scrollTop, document.body.scrollTop)
    }
 
    function E(e) {
        var t = m(e);
        return t >= w && t <= b + w
    }
 
    function S() {
        var e = document.createElement("audio");
        e.setAttribute("class", l);
        e.src = i;
        e.loop = false;
        e.addEventListener("canplay", function() {
            setTimeout(function() {
                x(k)
            }, 500);
            setTimeout(function() {
                N();
                p();
                for (var e = 0; e < O.length; e++) {
                    T(O[e])
                }
            }, 15500)
        }, true);
        e.addEventListener("ended", function() {
            N();
            h()
        }, true);
        e.innerHTML = " <p>If you are reading this, it is because your browser does not support the audio element. We recommend that you get a new browser.</p> <p>";
        document.body.appendChild(e);
        e.play()
    }
 
    function x(e) {
        e.className += " " + s + " " + o
    }
 
    function T(e) {
        e.className += " " + s + " " + u[Math.floor(Math.random() * u.length)]
    }
 
    function N() {
        var e = document.getElementsByClassName(s);
        var t = new RegExp("\\b" + s + "\\b");
        for (var n = 0; n < e.length; ) {
            e[n].className = e[n].className.replace(t, "")
        }
    }
 
    var e = 30;
    var t = 30;
    var n = 350;
    var r = 350;
    var i = "//s3.amazonaws.com/moovweb-marketing/playground/harlem-shake.mp3";
    var s = "mw-harlem_shake_me";
    var o = "im_first";
    var u = ["im_drunk", "im_baked", "im_trippin", "im_blown"];
    var a = "mw-strobe_light";
    var f = "//s3.amazonaws.com/moovweb-marketing/playground/harlem-shake-style.css";
    var l = "mw_added_css";
    var b = g();
    var w = y();
    var C = document.getElementsByTagName("*");
    var k = null;
    for (var L = 0; L < C.length; L++) {
        var A = C[L];
        if (v(A)) {
            if (E(A)) {
                k = A;
                break
            }
        }
    }
    if (A === null) {
        console.warn("Could not find a node of the right size. Please try a different page.");
        return
    }
    c();
    S();
    var O = [];
    for (var L = 0; L < C.length; L++) {
        var A = C[L];
        if (v(A)) {
            O.push(A)
        }
    }
})()    '>High一下</a> </li>
{% endmacro %}

cms/templates/search.html
{% extends 'base.html' %}
{% from 'bootstrap/pagination.html' import render_pagination %}
{% from 'macros.html' import category_card, post_card with context %}

{% block title %}Search: {{ q }}{% endblock %}

{% block content %}
    <div class="page-header">
        <h1>Search: {{ q }}</h1>
    </div>
    <div class="row">
        <div class="col-md-3">
            <div class="nav nav-pills flex-column" role="tablist" aria-orientation="vertical">
                <a class="nav-item nav-link {% if what == 'title' %}active{% endif %}"
                   href="{{ url_for('blog.search', q=q, what='title') }}">Title</a>
                <a class="nav-item nav-link {% if what == 'category' %}active{% endif %}"
                   href="{{ url_for('blog.search', q=q, what='category') }}">Category</a>
            </div>
        </div>

        <div class="col-md-9">
            {% if results %}
                <h5>{{ results|length }} results</h5>
                {% for item in results %}
                    {% if what == 'category' %}
                        {{ category_card(item) }}
                    {% else %}
                        {{ post_card(item) }}
                    {% endif %}
                {% endfor %}
            {% else %}
                <h5 class="tip">No results.</h5>
            {% endif %}
        </div>
    </div>
    {% if results %}
        <div class="page-footer">
            {{ render_pagination(pagination, align='right') }}
        </div>
    {% endif %}
{% endblock %}