cms/blueprints/admin.py
# -*- coding: utf-8 -*-

from flask import Blueprint, render_template, url_for, redirect, request, flash, current_app
from flask_login import login_required, current_user

from cms.extensions import db
from cms.forms import SettingForm, PostForm, CategoryForm, LinkForm
from cms.utils import redirect_back
from cms.models import Post, Category, Comment, Admin, Link

# 创建蓝本，第一个参数为蓝本的名称，第二个参数是包或模块的名称
# 使用__name__方便判断蓝本的根目录，寻找模板文件夹和静态文件夹
admin_bp = Blueprint('admin',__name__)

@admin_bp.route('/settings', methods=['POST', 'GET'])
@login_required
def settings():
    form = SettingForm()
    if form.validate_on_submit():
        current_user.name = form.name.data
        current_user.blog_title = form.blog_title.data
        current_user.blog_sub_title = form.blog_sub_title.data
        current_user.about = form.about.data
        db.session.commit()
        flash('Setting updated.', 'success')
        return redirect(url_for('blog.index'))
    form.name.data = current_user.name
    form.blog_title.data = current_user.blog_title
    form.blog_sub_title.data = current_user.blog_sub_title
    form.about.data = current_user.about
    return render_template('admin/settings.html', form=form)

# ----------------------------------------------------------------------------------

@admin_bp.route('/post/manage')
@login_required
def manage_post():
    page = request.args.get('page', 1, type=int)
    pagination = Post.query.order_by(Post.timestamp.desc()).paginate(page, per_page=current_app.config['CMS_MANAGE_POST_PER_PAGE'])
    posts = pagination.items
    return render_template('/admin/manage_post.html', pagination=pagination, posts=posts, page=page)

@admin_bp.route('/post/new', methods=['GET', 'POST'])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        title = form.title.data
        body = form.body.data
        category = Category.query.get(form.category.data)
        post = Post(title=title, body=body, category=category)
        db.session.add(post)
        db.session.commit()
        flash('Post created !', 'sucess')
        return redirect(url_for('blog.show_post', post_id=post.id))
    return render_template('/admin/new_post.html', form=form)

@admin_bp.route('/post/<int:post_id>/edit', methods=['GET', 'POST'])
@login_required
def edit_post(post_id):
    form = PostForm()
    # 获取对应文章id
    post = Post.query.get_or_404(post_id)
    if form.validate_on_submit():
        post.title = form.title.data
        post.body = form.body.data
        post.category = Category.query.get(form.category.data)
        db.session.commit()
        flash('Post updated.', 'success')
        return redirect(url_for('blog.show_post', post_id=post.id))
    form.title.data = post.title
    form.body.data = post.body
    form.category.data = post.category_id 
    return render_template('/admin/edit_post.html', form=form)

@admin_bp.route('/post/<int:post_id>/delete', methods=['POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    db.session.delete(post)
    db.session.commit()
    flash('Post delete.','success')
    return redirect_back()

# ----------------------------------------------------------------------------------

@admin_bp.route('/post/<int:post_id>/set-comment', methods=['POST'])
@login_required
def set_comment(post_id):
    post = Post.query.get_or_404(post_id)
    if post.can_comment:
        post.can_comment = False
        flash('Comment disabled.','info')
    else:
        post.can_comment = True
        flash('Comment enabled.','info')
    db.session.commit()
    return redirect(url_for('blog.show_post', post_id=post.id))

@admin_bp.route('/comment/manage')
@login_required
def manage_comment():
    filter_rule = request.args.get('filter', 'all') # 获取过滤规则，以显示不同的评论
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['CMS_COMMENT_PER_PAGE']

    if filter_rule == 'unread':
        filtered_comments = Comment.query.filter_by(reviewed=False)
    elif filter_rule == 'admin':
        filtered_comments = Comment.query.filter_by(from_admin=True)
    else:
        filtered_comments = Comment.query
    
    pagination = filtered_comments.order_by(Comment.timestamp.desc()).paginate(page, per_page=per_page)
    comments = pagination.items

    return render_template('/admin/manage_comment.html', comments=comments, pagination=pagination)

@admin_bp.route('/comment/<int:comment_id>/approve', methods=['POST'])
@login_required
def approve_comment(comment_id):
    comment = Comment.query.get_or_404(comment_id)
    comment.reviewed = True
    db.session.commit()
    flash('Comment published.','success')
    return redirect_back()


@admin_bp.route('/comment/<int:comment_id>/delete', methods=['POST'])
@login_required
def delete_comment(comment_id):
    comment = Comment.query.get_or_404(comment_id)
    db.session.delete(comment)
    db.session.commit()
    flash('Comment deleted.','success')
    return redirect_back()

# ----------------------------------------------------------------------------------

@admin_bp.route('/category/manage')
@login_required
def manage_category():
    return render_template('admin/manage_category.html')


@admin_bp.route('/category/new', methods=['GET', 'POST'])
@login_required
def new_category():
    form = CategoryForm()
    form = CategoryForm()
    if form.validate_on_submit():
        name = form.name.data
        category = Category(name=name)
        db.session.add(category)
        db.session.commit()
        flash('Category created.', 'success')
        return redirect(url_for('.manage_category'))
    return render_template('admin/new_category.html', form=form)


@admin_bp.route('/category/<int:category_id>/edit', methods=['GET', 'POST'])
@login_required
def edit_category(category_id):
    form = CategoryForm()
    category = Category.query.get_or_404(category_id)
    if category_id == 1:
        flash('You can not edit the default category.', 'warning')
        return redirect(url_for('blog.index'))
    if form.validate_on_submit():
        category.name = form.name.data
        db.session.commit()
        flash('Category updated.','success')
        return redirect(url_for('.manage_category'))
    form.name.data = category.name
    return render_template('admin/edit_category.html', form=form)


@admin_bp.route('/category/<int:category_id>/delete', methods=['POST'])
@login_required
def delete_category(category_id):
    category = Category.query.get_or_404(category_id)
    if category.id == 1:
        flash('You can not delete the default category.', 'warning')
        return redirect(url_for('blog.index'))
    category.delete() # 此方法已在category model中定义
    flash('Category deleted.', 'success')
    return redirect(url_for('.manage_category'))

# ----------------------------------------------------------------------------------

@admin_bp.route('/link/manage')
@login_required
def manage_link():
    return render_template('admin/manage_link.html')


@admin_bp.route('/link/new', methods=['GET', 'POST'])
@login_required
def new_link():
    form = LinkForm()
    if form.validate_on_submit():
        name = form.name.data
        url = form.url.data
        icon = form.icon.data
        link = Link(name=name, url=url, icon=icon)
        db.session.add(link)
        db.session.commit()
        flash('Link created.', 'success')
        return redirect(url_for('.manage_link'))
    return render_template('admin/new_link.html', form=form)


@admin_bp.route('/link/<int:link_id>/edit', methods=['GET', 'POST'])
@login_required
def edit_link(link_id):
    form = LinkForm()
    link = Link.query.get_or_404(link_id)
    if form.validate_on_submit():
        link.name = form.name.data
        link.url = form.url.data
        link.icon = form.name.data
        db.session.commit()
        flash('Link updated.', 'success')
        return redirect(url_for('.manage_link'))
    form.name.data = link.name
    form.url.data = link.url
    form.icon.data = link.icon
    return render_template('admin/edit_link.html', form=form)


@admin_bp.route('/link/<int:link_id>/delete', methods=['POST'])
@login_required
def delete_link(link_id):
    link = Link.query.get_or_404(link_id)
    db.session.delete(link)
    db.session.commit()
    flash('Link deleted.', 'success')
    return redirect(url_for('.manage_link'))

cms/blueprints/blog.py
# -*- coding: utf-8 -*-

from flask import render_template, flash, redirect, url_for, request, current_app, Blueprint, abort, make_response
from flask_login import current_user

from cms.emails import send_new_comment_email, send_new_reply_email
from cms.extensions import db
from cms.forms import CommentForm, AdminCommentForm
from cms.models import Post, Category, Comment
from cms.utils import redirect_back

blog_bp = Blueprint('blog', __name__)



@blog_bp.route('/')
def index():
    """ posts = Post.query.order_by(Post.timestamp.desc()).all() """
    page = request.args.get('page', 1, type=int) # 通过查询字符串获取当前页数
    per_page = current_app.config['CMS_POST_PER_PAGE'] # 每页数量
    # paginate方法的page默认值为1，per_page的默认值为20,pagination为分页对象
    pagination = Post.query.order_by(Post.timestamp.desc()).paginate(page, per_page=per_page)
    posts = pagination.items # 当前页数的记录列表
    return render_template('blog/index.html', pagination=pagination, posts=posts)

@blog_bp.route('/about')
def about():
    return render_template('blog/about.html')

@blog_bp.route('/category/<int:category_id>')
def show_category(category_id):
    category = Category.query.get_or_404(category_id)
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['CMS_POST_PER_PAGE']
    # 使用with_parent筛选所属分类文章
    pagination = Post.query.with_parent(category).order_by(Post.timestamp.desc()).paginate(page, per_page)
    posts = pagination.items
    return render_template('blog/category.html', category=category, pagination=pagination, posts=posts)

@blog_bp.route('/post/<int:post_id>', methods=['GET', 'POST'])
def show_post(post_id):
    post = Post.query.get_or_404(post_id)
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['CMS_COMMENT_PER_PAGE']
    # 通过filter_by过滤器获取通过审核的评论
    pagination = Comment.query.with_parent(post).filter_by(reviewed=True).order_by(Comment.timestamp.asc()).paginate(
        page, per_page)
    # 评论分页
    comments = pagination.items

    if current_user.is_authenticated: # 已登录，使用管理员表单
        form = AdminCommentForm()
        form.author.data = current_user.name
        form.email.data = current_app.config['CMS_EMAIL']
        form.site.data = url_for('.index')
        from_admin = True
        reviewed = True
    else:
        form = CommentForm()
        from_admin = False
        reviewed = False
    
    if form.validate_on_submit():
        author = form.author.data
        email = form.email.data
        site = form.site.data
        body = form.body.data
        comment = Comment(
            author=author, email=email, site=site, body=body,
            from_admin=from_admin, post=post, reviewed=reviewed
        )
        replied_id = request.args.get('reply')
        if replied_id:
            replied_comment = Comment.query.get_or_404(replied_id)
            comment.replied = replied_comment
            send_new_reply_email(replied_comment)
        db.session.add(comment)
        db.session.commit()
        
        # 消息闪现提醒
        if current_user.is_authenticated:
            flash('Comment published.', 'success')
        else:
            flash('Thanks, your comment will be published after reviewed.', 'info')
            # admin_email = current_app.config['CMS_EMAIL']
            send_new_comment_email(post)
        return redirect(url_for('.show_post', post_id=post_id))
    return render_template('blog/post.html', post=post, comments=comments, pagination=pagination, form=form)

# 回复功能
@blog_bp.route('/reply/comment/<int:comment_id>')
def reply_comment(comment_id):
    comment = Comment.query.get_or_404(comment_id)
    if not comment.post.can_comment:
        flash('Comment is disabled.', 'warning')
        return redirect(url_for('.show_post', post_id=comment.post.id))
    return redirect(
        url_for('.show_post', post_id=comment.post_id, reply=comment_id, author=comment.author) + '#comment-form')

# 主题切换
@blog_bp.route('/change-theme/<theme_name>')
def change_theme(theme_name):
    if theme_name not in current_app.config['CMS_THEMES'].keys():
        abort(404)
    
    response = make_response(redirect_back()) # 生成一个重定向啊应
    response.set_cookie('theme', theme_name, max_age=30*24*60*60)
    return response

# 搜索功能
@blog_bp.route('/search')
def search():
    q = request.args.get('q', '')
    if q == '':
        flash('Enter keywords about category or post title', 'warning')
        return redirect_back()
    
    # 获取查询类型，再模板中给出
    what = request.args.get('what', 'title')
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['CMS_POST_PER_PAGE']

    if what == 'title':
        pagination = Post.query.whooshee_search(q).paginate(page, per_page)
    elif what == 'category':
        pagination = Category.query.whooshee_search(q).paginate(page, per_page)
    else:
        redirect_back()

    results = pagination.items

    return render_template('search.html', q=q, results=results, pagination=pagination, what=what)

# 文章归档
@blog_bp.route('/archive')
def archive():
    """按时间归档文章"""
    posts = Post.query.order_by(Post.timestamp.desc()).all()
    # 按月份分组所有post
    data = {}
    years = reversed(list(set([post.timestamp.year for post in posts])))
    for year in years:
        months = reversed(list(set([post.timestamp.month for post in posts if post.timestamp.year == year])))
        for month in months:
            post_items = [post for post in posts if post.timestamp.month == month]
            data[(year, month)] = post_items
    return render_template('blog/archive.html', data=data)

cms/templates/blog/_posts.html
{# 文章摘要列表 #}
{% if posts %}
    {% for post in posts %}
        <h3 class="text-primary"><a href="{{ url_for('.show_post', post_id=post.id) }}">{{ post.title }}</a></h3>
        <span>{{ moment(post.timestamp).format('LL') }}</span>
        <p>
            {{ post.body|striptags|truncate }}
        </p>
        <small>
            Comments: <a href="{{ url_for('.show_post', post_id=post.id) }}#comments">{{ post.comments|length }}</a>&nbsp;&nbsp;
            Category: <a
                href="{{ url_for('.show_category', category_id=post.category.id) }}">{{ post.category.name }}</a>
            <span class="float-right"><small><a class="btn btn-primary btn-sm" href="{{ url_for('.show_post', post_id=post.id) }}">Read More</a></small></span>
        </small>
        {% if not loop.last %}
            <hr size="5" color="green">
        {% endif %}
    {% endfor %}
{% else %}
    <div class="tip">
        <h5>No posts yet.</h5>
        {% if current_user.is_authenticated %}
            <a href="{{ url_for('admin.new_post') }}">Write Now</a>
        {% endif %}
    </div>
{% endif %}

cms/templates/blog/_sidebar.html
<!-- banner -->
<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
        <!-- Wrapper for slides -->
        <div class="carousel-inner" role="listbox">
            <div class="carousel-item active">
                <img src="https://img.shan333.cn/images/2019/04/26/1.png">
            </div>

            <div class="carousel-item">
                <img src="https://img.shan333.cn/images/2019/04/26/3.png">
            </div>
            
            <div class="carousel-item">
                <img src="https://img.shan333.cn/images/2019/04/26/2.png">
            </div>
        </div>
      
        <!-- Controls -->
        <a class="carousel-control-prev" href="#carousel-example-generic" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon"></span>
        </a>
        <a class="carousel-control-next" href="#carousel-example-generic" role="button" data-slide="next">
                <span class="carousel-control-next-icon"></span>
        </a>
</div>

{# 侧边栏（分类） #}
{% if categories %}
<div class="card mb-3">
    <div class="card-header"><i class="fas fa-folder-open fa-fw"></i>Categories</div>
    <ul class="list-group list-group-flush">
        {% for category in categories %}
            <li class="list-group-item list-group-item-action d-flex justify-content-between align-items-center">
                <a href="{{ url_for('.show_category', category_id=category.id) }}">
                    {{ category.name }}
                </a>
                <span class="badge badge-primary badge-pill">{{ category.posts|length }}</span>
            </li>
        {% endfor %}
    </ul>
</div>
{% endif %}

{% if links %}
    <div class="card mb-3">
        <div class="card-header"><li class="fas fa-medal fa-fw"></li>Links</div>
        <ul class="list-group list-group-flush">
            {% for link in links %}
                <li class="list-group-item  list-group-item-action d-flex justify-content-between align-items-center">
                    <a href="{{ link.url }}" target="_blank">
                        <i class="{{ link.icon }}"></i>
                        {{ link.name }}
                    </a>
                </li>
            {% endfor %}
        </ul>
    </div>
{% endif %}

<div class="dropdown">
    <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenuButton"
            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Change Theme
    </button>
    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
        {% for theme_name, display_name in config.CMS_THEMES.items() %}
            <a class="dropdown-item"
               href="{{ url_for('blog.change_theme', theme_name=theme_name, next=request.full_path) }}">
                {{ display_name }}</a>
        {% endfor %}
    </div>
</div>

cms/templates/blog/about.html
{% extends 'base.html' %}

{% block title %}About{% endblock %}

{% block content %}
    <div class="page-header">
        <h1>About</h1>
    </div>
    <div class="row">
        <div class="col-sm-8">
            {{ admin.about|safe }}
        </div>
        <div class="col-sm-4 sidebar">
            {% include "blog/_sidebar.html" %}
        </div>
    </div>
{% endblock %}

cms/templates/blog/archive.html
{% extends 'base.html' %}

{% block title %}Archive{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
            {% for (date, posts) in data.items() %}
            <div class="row mb-8">
                <div class="col">
                    <h3>{{ date[0] }}年{{ date[1] }}月（{{ posts|length }}）</h3>
                    <ul class="list-group list-group-flush">
                    {% for post in posts %}
                        <li class="list-group-item list-group-item-action">
                            <a href="{{ url_for('blog.show_post', post_id=post.id) }}">{{ post.title }}</a>&nbsp;
                            <span class="text-muted">{{ moment(post.timestamp).format('YYYY-MM-DD') }}</span>
                        </li>
                    {% endfor %}
                    </ul>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

cms/templates/blog/category.html
{% extends 'base.html' %}
{% from 'bootstrap/pagination.html' import render_pagination %}

{% block title %}{{ category.name }}{% endblock %}

{% block content %}
    <div class="page-header">
        <h1>Category: {{ category.name }}</h1>
        <p class="text-muted">{{ category.posts|length }} posts</p>
    </div>
    <div class="row">
        <div class="col-sm-8">
            {% include "blog/_posts.html" %}
            <div class="page-footer">{{ render_pagination(pagination) }}</div>
        </div>
        <div class="col-sm-4 sidebar">
            {% include "blog/_sidebar.html" %}
        </div>
    </div>
{% endblock %}

cms/templates/blog/index.html
{% extends 'base.html' %}
{% from 'macros.html' import high %}
{% from 'bootstrap/pagination.html' import render_pager %}

{% block title %}Home{% endblock %}

{% block content %}
    <div class="page-header">
        <h1 class="display-3">{{ admin.blog_title|default('Blog Title') }}</h1>
        <h4 class="text-muted">&nbsp;{{ admin.blog_sub_title|default('Blog Subtitle') }}</h4>
    </div>
    <div class="row">
        <div class="col-sm-8">
            {% include 'blog/_posts.html' %}
            {% if posts %}
                <div class="page-footer">{{ render_pager(pagination) }}</div>
            {% endif %}
        </div>
        <div class="col-sm-4 sidebar">
            {% include 'blog/_sidebar.html' %}
            {{ high() }}
        </div>
    </div>
{% endblock %}

cms/templates/blog/post.html
{# 文章主体部分 #}
{% extends 'base.html' %}
{% from 'bootstrap/form.html' import render_form %}
{% from 'bootstrap/pagination.html' import render_pagination %}

{% block title %}{{ post.title }}{% endblock %}

{% block content %}
    <div class="page-header">
        <h1>{{ post.title }}
            <span class="float-right">
                {% if current_user.is_authenticated %}
                    <a class="btn btn-info btn-sm" href="{{ url_for('admin.edit_post', post_id=post.id) }}">Edit</a>
                    <form class="inline" method="post"
                          action="{{ url_for('admin.delete_post', post_id=post.id, next=url_for('blog.index')) }}">
                        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
                        <button type="submit" class="btn btn-danger btn-sm" onclick="return confirm('Are you sure?');">Delete
                        </button>
                    </form>
                {% endif %}
            </span>
        </h1>
        <small>
            Category: <a
                href="{{ url_for('.show_category', category_id=post.category.id) }}">{{ post.category.name }}</a><br>
            Date: {{ moment(post.timestamp).format('LL') }}
        </small>
    </div>
    <div class="row">
        <div class="col-sm-8">
            {{ post.body|safe }}
            <hr>
            <!-- 文章分享模态框 -->
            <button type="button" class="btn btn-primary btn-sm" data-toggle="modal" data-target=".postLinkModal">Share
            </button>
            <div class="modal fade postLinkModal" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel"
                 aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalLabel">Permalink</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <div class="form-group">
                                <input type="text" class="form-control"
                                       value="{{ url_for('.show_post', post_id=post.id, _external=True) }}" readonly>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="comments" id="comments">
                <h3>{{ pagination.total }} Comments
                    <small>
                        <a href="{{ url_for('.show_post', post_id=post.id, page=pagination.pages or 1) }}#comments">
                            latest</a>
                    </small>
                    <!-- 评论区开关表单 -->
                    {% if current_user.is_authenticated %}
                        <form class="float-right" method="post"
                              action="{{ url_for('admin.set_comment', post_id=post.id, next=request.full_path) }}">
                            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
                            <button type="submit" class="btn btn-warning btn-sm">
                                {% if post.can_comment %}Disable{% else %}Enable{% endif %} Comment
                            </button>
                        </form>
                    {% endif %}
                </h3>
                {% if comments %}
                    <ul class="list-group">
                        {% for comment in comments %}
                            <li class="list-group-item list-group-item-action flex-column">
                                <div class="d-flex w-100 justify-content-between">
                                    <h5 class="mb-1">
                                        <a href="{% if comment.site %}{{ comment.site }}{% else %}#{% endif %}"
                                           target="_blank">
                                            {% if comment.from_admin %}
                                                {{ admin.name }}
                                            {% else %}
                                                {{ comment.author }}
                                            {% endif %}
                                        </a>
                                        {% if comment.from_admin %}
                                            <span class="badge badge-primary">Author</span>{% endif %}
                                        {% if comment.replied %}<span class="badge badge-light">Reply</span>{% endif %}
                                    </h5>
                                    <small data-toggle="tooltip" data-placement="top" data-delay="500"
                                           data-timestamp="{{ comment.timestamp.strftime('%Y-%m-%dT%H:%M:%SZ') }}">
                                        {{ moment(comment.timestamp).fromNow() }}
                                    </small>
                                </div>
                                {% if comment.replied %}
                                    <p class="alert alert-dark reply-body">{{ comment.replied.author }}:
                                        <br>{{ comment.replied.body }}
                                    </p>
                                {%- endif -%}
                                <p class="mb-1">{{ comment.body }}</p>
                                <div class="float-right">
                                    <a class="btn btn-light btn-sm"
                                       href="{{ url_for('.reply_comment', comment_id=comment.id) }}">Reply</a>
                                    <!-- 评论删除控件 -->
                                    {% if current_user.is_authenticated %}
                                       <a class="btn btn-light btn-sm" href="mailto:{{ comment.email }}">Email</a>
                                       <form class="inline" method="post"
                                             action="{{ url_for('admin.delete_comment', comment_id=comment.id, next=request.full_path) }}">
                                           <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
                                           <button type="submit" class="btn btn-danger btn-sm"
                                                   onclick="return confirm('Are you sure?');">Delete
                                           </button>
                                       </form>
                                   {% endif %}
                                </div>
                            </li>
                        {% endfor %}
                    </ul>
                {% else %}
                    <div class="tip"><h5>No comments.</h5></div>
                {% endif %}
            </div>
            {% if comments %}
                {{ render_pagination(pagination, fragment='#comments') }}
            {% endif %}
            {% if request.args.get('reply') %}
                <div class="alert alert-dark">
                    Reply to <strong>{{ request.args.get('author') }}</strong>:
                    <a class="float-right" href="{{ url_for('.show_post', post_id=post.id) }}">Cancel</a>
                </div>
            {% endif %}
            <!-- 评论表单 -->
            {% if post.can_comment %}
                <div id="comment-form">
                    {{ render_form(form, action=request.full_path) }}
                </div>
            {% else %}
                <div class="tip"><h5>Comment disabled.</h5></div>
            {% endif %}
        </div>
        <div class="col-sm-4 sidebar">
            {% include "blog/_sidebar.html" %}
        </div>
    </div>
{% endblock %}